on:
  push:
    branches-ignore:
    - 'master'

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"

  integration:
    runs-on: ubuntu-latest
    needs: [label_pr]

    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2

    - name: Get labels assigned to PR of this branch
      id: pull_request_labels
      uses: ./
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    
    - name: Assert provided label is found
      if: contains(steps.pull_request_labels.outputs.labels, '"test-test"') != true
      run: exit 1

    - name: Assert not existing labels aren't found
      if: contains(steps.pull_request_labels.outputs.labels, '"test"')
      run: exit 1
